### ISSUE TITLE
Suggest to add a getMonthName() feature

### ISSUE THREAD

**Issue by clemcg** [sandypockets/easy-dates#1]
**Is your feature request related to a problem? Please describe.**
I suggest to add a `getMonthName()` function.

**Describe the solution you'd like**
Calling `getMonthName()` would return the name of the month in English.
It could also be possible to imagine a language such as "en", "fr" or "de" to be passed as a parameter (Example: `getMonthName(fr)`) to provide the month name in local language.

**Describe alternatives you've considered**
Alternative could be to set-up a array containing the month names and refer to this array with its index.
For example `month[0]` would return `"Jan"` or `month[11]` would return `"Dec"`.

**Additional context**
Congrats' on this library, I think it is super useful and straight to the point. Thanks for the work provided.

**Comment by sandypockets** [comment]
Hey @clemcg! Thanks for your kind words and suggestion. I think that's a great idea, and have gone ahead and implemented it, and released the newest version to NPM. 

You can check out the new docs for this function [on this page](https://easy-dates.dev/docs/functions/getMonthName), but I've sort of meshed both of your ideas together. 

```javascript
getMonthName(local, index, short);
```

If you don't include any arguments, then it defaults to `en` locale, the current month's index, and `short` set to `false`, which means it will return the full month name. 

Alternatively if you have a particular month in mind, then you can include an `index` for it. Note that whenever you include an index, you must include a `locale` too.

```javascript
 getMonthName("en", "3") // April
```

You can check out a live example of this new function near the last line of [this StackBlitz](https://stackblitz.com/edit/easy-dates-demo?file=src/App.js)

Let me know if you had something else in mind, or feel free to submit a PR. Thanks again!

**Comment by clemcg** [comment]
Awesome ! It's super cool ! Congrats' 👍
